version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  worker:
    build: 
      context: ./ConsumerPedidos
      dockerfile: Dockerfile
    container_name: worker_leitura_registros
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
  
  api:
    build: 
      context: ./API
      dockerfile: Dockerfile
    container_name: api_relatorios
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
